# -*- coding: utf-8 -*-
"""TrainingDecisionTree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCB4qym5uLUruJh1TvBE12PhOOnHcaBT

<a href="https://colab.research.google.com/github/MuhammadMirafuddin17/PRIVATE/blob/main/TrainingDecisionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

INSTAL LIBRARY YANG DIPERLUKAN
"""

!pip install scikit-learn pandas joblib

"""IMPORT LIBRARY"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import joblib

"""UPLOAD DATASET"""

from google.colab import files
uploaded = files.upload()

"""READ DATASET"""

df = pd.read_csv("mushrooms.csv")

"""ENCODE SEMUA FITUR KATEGORIKAL"""

df_encoded = df.apply(LabelEncoder().fit_transform)

"""PISAHKAN FITUR DAN LABEL"""

X = df_encoded.drop("class", axis=1)
y = df_encoded["class"]

"""BAGI DATA MENJADI TRAINING DAN TESTING"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""BUAT DAN LATIH MODEL DECISION TREE C4.5 DENGAN ENTROPY"""

clf = DecisionTreeClassifier(criterion="entropy", random_state=42)
clf.fit(X_train, y_train)

"""SIMPAN MODEL DAN LABEL ENCODER"""

joblib.dump(clf, "decision_tree_model.pkl")
joblib.dump(LabelEncoder().fit(df["class"]), "label_encoder.pkl")

"""SIMPAN TEST DATA DAN UNTUK DIGUNAKAN PADA TESTING"""

X_test.to_csv("X_test.csv", index=False)
y_test.to_csv("y_test.csv", index=False)
print("Training selesai dan model disimpan.")